name: retrofit_example
description: example_protobuf
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  http_parser: ^4.0.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  protobuf: ^3.1.0
  retrofit:

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mock_web_server: ^5.0.0-nullsafety.1
  retrofit_generator:

dependency_overrides:
  retrofit:
    path: ../retrofit
  retrofit_generator:
    path: ../generator

flutter:
  uses-material-design: true
