name: Deploy latest docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: |
          cd annotation
          dartdoc
          mv doc/api ../public
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
